### ISSUE TITLE
container.lookup is not a function Ember@2.2.0

### ISSUE THREAD

**Issue by ZackMattor** [twokul/ember-cli-bugsnag#30]
This addon is using the Application Initializers API, which doesn't have access to `app.lookup` anymore. It should probably be migrated to be an instance initializer to access `app.lookup` as it fails in new ember versions.

It's fixed as easily as renaming `app/initializers` to `app/instance-initializers` I believe.

**Comment by luismendozamx** [comment]
+1 this is also happening to me after migrating to 2.2.0

**Comment by ZackMattor** [comment]
@luismendozamx feel free to look how i fixed it here. https://github.com/ZackMattor/ember-cli-bugsnag

If you wanna test it...

```
    "ember-cli-bugsnag": "https://github.com/ZackMattor/ember-cli-bugsnag.git#v0.0.12",
```

**Comment by luismendozamx** [comment]
Awesome! Thank you @ZackMattor

**Comment by ZackMattor** [comment]
Also... it looks like https://github.com/twokul/ember-cli-bugsnag/pull/22 might fix it too.
